# frozen_string_literal: true

source "https://rubygems.org"

# git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "rspec"
gem "sinatra"
gem "sinatra-contrib"
gem "sinatra-activerecord"
gem "bcrypt"
gem "sqlite3"
gem "pry"
gem "tzinfo-data"
gem "dotenv"
gem "rake"
gem "webrick"
gem "rack-test"
gem "rack-contrib"